services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: flyway_demo
      POSTGRES_USER: flyway_user
      POSTGRES_PASSWORD: flyway_pass
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
