name: Flyway Migrate Staging
on:
  push:
    branches: ['main']

jobs:
  migrate-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Flyway migration (Staging)
        run: |
          docker run --rm \
           -v $PWD/migrations:/flyway/sql \
           -v $PWD/conf:/flyway/conf \
           -e FLYWAY_USER=${{ secrets.STG_DB_USER }} \
           -e FLYWAY_PASS=${{ secrets.STG_DB_PASS }} \
           flyway/flyway:11.11 \
           -configFiles=/flyway/conf/flyway-staging.conf migrate
